name: flutter_sound_button
description: A customizable Flutter button widget that plays sound effects on press.
homepage: https://github.com/Sandun-Induranga/flutter_sound_button
repository: https://github.com/Sandun-Induranga/flutter_sound_button.git

version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/sounds/click.mp3
    - assets/sounds/beep.mp3
    - assets/sounds/chime.mp3
